{% set name = "wheel-inspect" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7df5a0223c39ba065a1eef6efa4ea575b825dad7f3399ee02aaaa888f07ca5e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wheel2json = wheel_inspect.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs >=18.1
    - entry-points-txt >=0.1.0
    - headerparser >=0.4.0
    - packaging >=17.1
    - python >=3.6
    - readme_renderer >=24.0
    - wheel-filename >=1.1

test:
  imports:
    - wheel_inspect
  source_files:
    - test/data/wheels/setuptools-36.0.1-py2.py3-none-any.whl
  commands:
    - wheel2json test/data/wheels/setuptools-36.0.1-py2.py3-none-any.whl

about:
  home: https://github.com/jwodder/wheel-inspect
  summary: Extract information from wheels
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
